import { TEMPERATURE_OPTIONS } from "./options";

const UNIT_TYPES_WITH_NEGATIVE_VALUES_ARRAY = [
    TEMPERATURE_OPTIONS.c,
    TEMPERATURE_OPTIONS.f
]

export const UNIT_TYPES_WITH_NEGATIVE_VALUES = new Set(UNIT_TYPES_WITH_NEGATIVE_VALUES_ARRAY);